### ISSUE TITLE
大佬 这个源码在 宝塔上咋部署呀?

### ISSUE THREAD

**Issue by 1f4a7n** [StreakingMan/solvable-sheep-game#1]

**Comment by StreakingMan** [comment]
之前没用过宝塔，刚去官网体验了下，网站直接代理的静态资源，项目内yarn build，把dist下的文件全部拷贝到你再宝塔上建的网站的根目录下就好了

**Comment by 2003lgx** [comment]
我把文件全部拷贝到根目录下了，打开网站，网站标签有文字但是网页内容不显示

**Comment by StreakingMan** [comment]
> 

执行 yarn build -> 把dist下的所有文件拷贝到站点根目录，不是直接把项目拷过去

**Comment by 2003lgx** [comment]
有打包好的吗，我设备有问题，打包的时候一直报错

**Comment by 2003lgx** [comment]
OK了弄好了

**Comment by jianghongdou** [comment]
还是不会弄，也没有手把手教的
