### ISSUE TITLE
想问一下累计访问的代码实现

### ISSUE THREAD

**Issue by Undertone0809** [StreakingMan/solvable-sheep-game#13]
想问一下这部分的累计访问的功能是怎么做的呀，看了下代码暂时没有看到这个功能实现的地方。
![image](https://user-images.githubusercontent.com/72488598/192603358-9bb1e7f8-5b4b-460a-be87-75d1e7aa8885.png)

**Comment by imMoonset** [comment]
调了个库好像，在index.html里面

**Comment by imMoonset** [comment]
> 想问一下这部分的累计访问的功能是怎么做的呀，看了下代码暂时没有看到这个功能实现的地方。 ![image](https://user-images.githubusercontent.com/72488598/192603358-9bb1e7f8-5b4b-460a-be87-75d1e7aa8885.png)

调了个库好像，在index.html里面

**Comment by StreakingMan** [comment]
用的是[不蒜子](https://busuanzi.ibruce.info/)哦，大概原理就是js文件加载完毕后，获取当前页面路径等信息，上报服务器，拿到相应的访问数据，然后查找固定id的dom把数据塞进去（所以要确保，不蒜子的js文件执行的时候，相应的dom要存在）

**Comment by Undertone0809** [comment]
> 用的是[不蒜子](https://busuanzi.ibruce.info/)哦，大概原理就是js文件加载完毕后，获取当前页面路径等信息，上报服务器，拿到相应的访问数据，然后查找固定id的dom把数据塞进去（所以要确保，不蒜子的js文件执行的时候，相应的dom要存在）

get到了，感谢！
