### ISSUE TITLE
等我好不容易上了个涩涩版，结果就上了自定义 /气哭

### ISSUE THREAD

**Issue by imMoonset** [StreakingMan/solvable-sheep-game#14]
https://y.uoxn.com/  

体验过的欢迎回复一哈~ /笑

**Comment by 623059008** [comment]
https://triple.epicanecdotes.games/

**Comment by 623059008** [comment]
二创了一下，有点整活，顺便搞了一下Electron版本
https://triple.epicanecdotes.games/

**Comment by StreakingMan** [comment]
> 二创了一下，有点整活，顺便搞了一下Electron版本 https://triple.epicanecdotes.games/

左右两边有啥关联嘛 😂

**Comment by 623059008** [comment]
> > 二创了一下，有点整活，顺便搞了一下Electron版本 https://triple.epicanecdotes.games/
> 
> 左右两边有啥关联嘛 

玩右边的有个进度，每1/4左边或更新代码，每一关过了之后左边会显示全部代码。
我本来准备做另一个功能，还没做完，就是每一关有两种通过方式，写出左边的题，或者通关右边的消消乐，准备加一个pyscripts
二创的本意就是想吐槽leetcode算法很难，像消消乐一样无穷无尽😂

**Comment by StreakingMan** [comment]
已开启 Discussions  欢迎移步分享二创和其他idea~
