### ISSUE TITLE
构建完后上传的宝塔

### ISSUE THREAD

**Issue by miloce** [StreakingMan/solvable-sheep-game#16]
为什么没有用![7RP4)}GVME(NG@}WG{LFDQS](https://user-images.githubusercontent.com/82767574/194034668-d089c34c-6742-4109-aa07-c4496b80f277.png)

**Comment by StreakingMan** [comment]
近期项目有调整，原先的打包文件以及不再适用，请参考这里 [diy指南](https://github.com/StreakingMan/solvable-sheep-game/blob/master/diy/README.md)
