### ISSUE TITLE
求助一些前端实现问题

### ISSUE THREAD

**Issue by PaParaZz1** [StreakingMan/solvable-sheep-game#19]
我们这边在搭建一个网页部署端（https://opendilab.net/sheep ），我之前没怎么接触过前端相关，所以有几个问题想求助下：
- 有时候失败或者通关的提示button会一闪而过，没操作什么就过去了
- 在有些收集和浏览器上打开上面的网址，会出现完全没东西，不显示的情况

**Comment by StreakingMan** [comment]
第一个问题我去DI-sheep项目看了下，大致是因为点击第七个卡片但失败时，前端和接口返回结果不一致
<img width="664" alt="image" src="https://user-images.githubusercontent.com/30397306/195652967-84da8431-7749-4ee0-8f81-5eaf167b0df7.png">
fetch时异步调用，下面的setFinished先执行，再是请求的回掉执行，这部分逻辑可以考虑以后端处理为准

第二个问题，需要提供更具体的信息进一步排查

此外，本项目已更新，核心逻辑做了单独抽离，ui也做了调整，可以考虑更新一波前端代码😄

**Comment by PaParaZz1** [comment]
感谢反馈！
- 第一个问题我明白了，现在已经修复
- 第二个问题，怎样给你提供相关的信息呢？比如找个不显示的设备，inspect看看相关信息？还是别的什么方式

**Comment by StreakingMan** [comment]
> 感谢反馈！
> 
> * 第一个问题我明白了，现在已经修复
> * 第二个问题，怎样给你提供相关的信息呢？比如找个不显示的设备，inspect看看相关信息？还是别的什么方式

嗯 提供下手机型号、浏览器版本等信息

**Comment by PaParaZz1** [comment]
目前出问题的环境有
- 手机：miui 12.5.7 红米k30；浏览器：VC（170010000），CID（86bd97b）
- 手机：miui13.0.23 红米k50 pro；浏览器：VC（170010000），CID（86bd97b）
- 手机：华为p40pro 鸿蒙 2.0.0 版本号：2.0.0.273 （C00E230R8P2）GPU Turbo ；浏览器：华为默认浏览器 版本12.1.3.303
- 电脑：macos monterey 12.0.1  m1pro芯片的mbp；浏览器：safari，版本15.1 (17612.2.9.1.20）

**Comment by StreakingMan** [comment]
无法复现，后续跟进（也可能是早期版本的bug)
