### ISSUE TITLE
演示网站，打不开

### ISSUE THREAD

**Issue by SaadBazaz** [StreakingMan/solvable-sheep-game#20]
问候，
我收到一条错误消息。我打开了演示网站，该网站位于以下链接： https://solvable-sheep-game.streakingman.com/

这是复制的错误消息：
``` 
当前应用url:/1/classes/file, 参数为:{"limit":["100"],"where":["{\"type\":\"default\"}"]}, 返回带宽大小(数据长度):383064, 系统限制值:204800, 带宽大小(数据长度)已超过bmob的限制，请升级套餐
稍后再试或 [返回首页](https://solvable-sheep-game.streakingman.com/)
```

这就是我所看到的 :
<img width="1387" alt="Screenshot 2022-11-03 at 3 48 43 PM" src="https://user-images.githubusercontent.com/51885228/199701994-5311aada-c9f0-4564-8ade-b6e0c2584af0.png">

请问我该如何解决？谢谢你。

**Comment by StreakingMan** [comment]
额这个是因为之前为了节省静态托管服务的流量  把一些音频文件转base64存后台数据库了  这两天后台服务套餐到期回到了之前的传输大小限制  现在已经把资源替换成外链，可以正常访问了
