### ISSUE TITLE
yarn build 报错，大佬能帮忙看看吗

### ISSUE THREAD

**Issue by lioumin1** [StreakingMan/solvable-sheep-game#3]
请教下大佬这报错是怎么回事呢

`D:\Downloads\Compressed\solvable-sheep-game-master>yarn build
yarn run v1.22.10
$ tsc && vite build
file:///D:/Downloads/Compressed/solvable-sheep-game-master/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by StreakingMan** [comment]
vite的报错，可能是node版本的问题，检查下node版本

vite官网的说明：
> 兼容性注意
>
> Vite 需要 [Node.js](https://nodejs.org/en/) 版本 14.18+，16+。然而，有些模板需要依赖更高的 Node 版本才能正常运行，当你> 的包管理器发出警告时，请注意升级你的 Node 版本。

我这边也会增加自动发布打包命令，将打包文件上传

**Comment by lioumin1** [comment]
> 

感谢大佬，更新node后可以打包了
