### ISSUE TITLE
这是什么原因，该怎么修复

### ISSUE THREAD

**Issue by a1017349504** [StreakingMan/solvable-sheep-game#4]
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by StreakingMan** [comment]
看起来是浏览器端的报错，能提供下浏览器的信息吗？

**Comment by zhangkejian0** [comment]
https://blog.csdn.net/qq_32590631/article/details/112016792

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
