### ISSUE TITLE
关卡上升后，弹出位置错乱

### ISSUE THREAD

**Issue by civetming** [StreakingMan/solvable-sheep-game#5]
关卡上升后，弹出位置错乱了
是否是  画布太小了 没有预留弹出的位置 而直接随机放回了

**Comment by StreakingMan** [comment]
目前的实现：弹出的位置y轴方向是固定在顶部，x轴方向随机的，切层叠的优先顺序相较于之前没有变化，这意味着弹出后的卡片是有可能被覆盖的

可以考虑专门预留而外的空间用于弹出，或者你有更好的想法欢迎pr😄
