### ISSUE TITLE
问个小白问题，项目怎么部署的啊，求大佬解答

### ISSUE THREAD

**Issue by zdg88** [StreakingMan/solvable-sheep-game#6]

**Comment by 1967024561** [comment]
同问

**Comment by StreakingMan** [comment]
纯前端项目，直接代理静态资源就可以了。这个仓库是直接用[verce](https://vercel.com/)l部署的（强烈安利，集成了很多模版，导入项目一键部署）。用其他方式部署的话，`yarn build` 以下将打包文件（dist下的）放到站点根目录就好了（目前项目发版会自动打包，dist可直接使用）

**Comment by jianghongdou** [comment]
> 纯前端项目，直接代理静态资源就可以了。这个仓库是直接用[verce](https://vercel.com/)l部署的（强烈安利，集成了很多模版，导入项目一键部署）。用其他方式部署的话， 以下将打包文件（dist下的）放到站点根目录就好了（目前项目发版会自动打包，dist可直接使用）`yarn build`

大佬能出个视频吗？，真的不会

**Comment by zdg88** [comment]
> 纯前端项目，直接代理静态资源就可以了。这个仓库是直接用[verce](https://vercel.com/)l部署的（强烈安利，集成了很多模版，导入项目一键部署）。用其他方式部署的话，`yarn build` 以下将打包文件（dist下的）放到站点根目录就好了（目前项目发版会自动打包，dist可直接使用）

感谢大佬，试了下vercel成功了，唯一一点就是容易被墙。

**Comment by StreakingMan** [comment]
> 

vercel的域名在微信里是被屏蔽的，可以用自己的域名，vercel支持的

**Comment by Undertone0809** [comment]
我甚至都部署成功了在vercel上面，还是无法使用，build 成功，但是部署的页面无法访问。我尝试跳转到我的域名下面，还是无法访问，不清楚是什么问题。

**Comment by Undertone0809** [comment]
> 

发现了，重定向之后要等待一会才可以访问。感谢博主分享vercel，之前用的gitlab上面的。

**Comment by Undertone0809** [comment]
> 我甚至都部署成功了在vercel上面，还是无法使用，build 成功，但是部署的页面无法访问。我尝试跳转到我的域名下面，还是无法访问，不清楚是什么问题。

发现了，重定向之后要等待一会才可以访问。感谢博主分享vercel，之前用的gitlab上面的。
