### ISSUE TITLE
二次开发的一些问题

### ISSUE THREAD

**Issue by PaParaZz1** [StreakingMan/solvable-sheep-game#9]
非常感谢你的项目！！！
我在你的项目基础上，搞了一个AI（基于深度强化学习）玩这个的 repo：[DI-sheep](https://github.com/opendilab/DI-sheep)。
想问下像现在这样在 README 里[致谢标注](https://github.com/opendilab/DI-sheep#%E8%87%B4%E8%B0%A2)你的 repo 可以吗？以及你有没有什么其他创意和想法，一起试试 AI + 这个游戏的更多想法？

**Comment by StreakingMan** [comment]
嗯这样可以的。深度学习我一直很感兴趣，但一直是从入门到放弃，希望老哥带带我！
DI-sheep我大致看了下README：
1. 游戏的状态这边可以尝试暴露api
2. 3tiles的道具我这边也可以提供支持
3. 牌的层数问题，我的实现其实并没有分图层，只是遍历一维数组，向后做了覆盖判断。如果ai需要考虑往后几步的情况，可以考虑根据覆盖的层数，改变卡片的透明度活背景色，方便ai识别（或说ai是基于图像识别还是直接检测浏览器dom啊？)

**Comment by PaParaZz1** [comment]
好的好的

1. 游戏本身其实我是以你的代码为基础，直接魔改了个[python版](https://github.com/opendilab/DI-sheep/blob/master/service/sheep_env.py)，所以训练其实只用python就行，react只是作为渲染工具
2. 道具这个点很有意思，可以一起想想有什么道具比较有意思，且适合让AI来学
3. 牌的层数这个事情有点烦，嗯我理解你现在这个实现方式的，我目前也是按你这样搞的
4. 入坑深度学习这个事很欢迎啊，我明天开始会逐步写一些DI-sheep里设计神经网络和强化学习算法的分析，可以保持关注并提提建议，怕写的不够简明

P.S. 可以把DI-sheep的链接挂在你的repo的README里吗，比如Related Repo这样？

**Comment by StreakingMan** [comment]
> 好的好的
> 
> 1. 游戏本身其实我是以你的代码为基础，直接魔改了个[python版](https://github.com/opendilab/DI-sheep/blob/master/service/sheep_env.py)，所以训练其实只用python就行，react只是作为渲染工具
> 2. 道具这个点很有意思，可以一起想想有什么道具比较有意思，且适合让AI来学
> 3. 牌的层数这个事情有点烦，嗯我理解你现在这个实现方式的，我目前也是按你这样搞的
> 4. 入坑深度学习这个事很欢迎啊，我明天开始会逐步写一些DI-sheep里设计神经网络和强化学习算法的分析，可以保持关注并提提建议，怕写的不够简明
> 
> P.S. 可以把DI-sheep的链接挂在你的repo的README里吗，比如Related Repo这样？

不好意思才看到，链接已挂，十分荣幸！
